"""LoadLedger's mounted tables, the window-park clock, and two ceilings widened to BigInteger

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-04 00:00:00.000000

Phase 5, and the **first package-table mount in this application** (ADR-0050). What that pattern
asks of a host is exactly this file plus the one unconditional
``mount_ledger_tables(Base.metadata)`` call at the bottom of
``promptcadence.infrastructure.db.models``: the package ships table *shapes* and never a migration
history, so its four tables appear in PromptCadence's own autogenerate diff, upgrade with
PromptCadence's own history, and are backed up, restored and pruned by whoever owns this database.
Commissioner's ``egress_decisions`` mount at Phase 6 and CutCtx's later one copy this shape.

Three details are contract rather than style, and a later mount must keep all three:

* **The prefix is the package's default** (``ledger_``). It is part of the mounted contract:
  changing it once a deployment has migrated is a table rename, not a configuration change.
* **The DDL below is autogenerated against the mount, not transcribed from the package.** The
  parity test (``check_parity`` over ``Base.metadata``) is what proves the two agree, on both
  dialects, and it is the reason nothing here may be hand-tuned.
* **Every accumulating integer is a BigInteger.** That is LoadLedger's own rule and this revision
  applies it to two columns of PromptCadence's own that predate the ledger and got it wrong:
  ``trajectories.budget_money_nanos`` and ``trajectories.budget_token_ceiling`` were ``Integer``.
  :class:`baseaicore.Money` is whole *nanos*, so the shipped $5.00 default ceiling is
  5 000 000 000 — already past a 4-byte integer's 2 147 483 647. SQLite's dynamic typing stores it
  regardless, so no SQLite test could ever have caught it; on PostgreSQL every trajectory carrying
  a money ceiling over $2.14 would have failed to insert. Widened here, in the revision that first
  makes those columns bind anything.

``trajectories`` also gains the ``awaiting_window`` clock the domain has carried since Phase 2:
``window_parked_from``, ``window_next_edge_at`` and ``window_days_waited`` are
``domain.trajectory.WindowWait`` field for field. It is persisted rather than computed from process
start because lifecycle §8.1 requires a restart to resume on the same UTC-day edge, and because
T17's halt counts *day edges that passed*, which a recomputed clock cannot know. ``budget_partial_
pricing`` is the per-request override of ``[budget] partial_pricing`` (ADR-0069), nullable because
``NULL`` means "the configured default", which is not the same as either value.
"""

from __future__ import annotations

import sqlalchemy as sa
import weightsdb
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    op.create_table(
        "ledger_entries",
        sa.Column("entry_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("source_ref", sa.String(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("unpriced", sa.Boolean(), nullable=False),
        sa.Column("pricing_hash", sa.String(), nullable=True),
        sa.Column("debit_json", sa.Text(), nullable=False),
        sa.Column("verdicts_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("entry_id", name="pk_ledger_entries"),
    )
    op.create_index("ix_ledger_entries_occurred_at", "ledger_entries", ["occurred_at"])
    op.create_index("ix_ledger_entries_run", "ledger_entries", ["run_id", "entry_id"])
    op.create_table(
        "ledger_balances",
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("window_key", sa.String(), nullable=False),
        sa.Column("tokens_spent", sa.BigInteger(), nullable=False),
        sa.Column("unpriced_debit_count", sa.BigInteger(), nullable=False),
        sa.Column("untotalled_debit_count", sa.BigInteger(), nullable=False),
        sa.Column("unmetered_debit_count", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("scope", "window_key", name="pk_ledger_balances"),
    )
    op.create_table(
        "ledger_balance_money",
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("window_key", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("nanos_spent", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("scope", "window_key", "currency", name="pk_ledger_balance_money"),
    )
    op.create_table(
        "ledger_runs",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("declared_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("run_id", name="pk_ledger_runs"),
    )
    with op.batch_alter_table("trajectories") as batch:
        batch.add_column(sa.Column("budget_partial_pricing", sa.String(length=10), nullable=True))
        batch.add_column(sa.Column("window_parked_from", sa.String(length=30), nullable=True))
        batch.add_column(sa.Column("window_next_edge_at", weightsdb.UtcDateTime(), nullable=True))
        batch.add_column(
            sa.Column(
                "window_days_waited", sa.Integer(), nullable=False, server_default=sa.text("0")
            )
        )
        batch.alter_column(
            "budget_money_nanos",
            existing_type=sa.Integer(),
            type_=sa.BigInteger(),
            existing_nullable=True,
        )
        batch.alter_column(
            "budget_token_ceiling",
            existing_type=sa.Integer(),
            type_=sa.BigInteger(),
            existing_nullable=True,
        )
    # The server default did its job -- filling the column on rows that already existed. Dropping
    # it keeps the model (a Python-side ``default=0``) and the schema in parity; a lingering
    # server default is a difference ``check_parity`` reports forever.
    with op.batch_alter_table("trajectories") as batch:
        batch.alter_column("window_days_waited", server_default=None)


def downgrade() -> None:
    with op.batch_alter_table("trajectories") as batch:
        batch.alter_column(
            "budget_token_ceiling",
            existing_type=sa.BigInteger(),
            type_=sa.Integer(),
            existing_nullable=True,
        )
        batch.alter_column(
            "budget_money_nanos",
            existing_type=sa.BigInteger(),
            type_=sa.Integer(),
            existing_nullable=True,
        )
        batch.drop_column("window_days_waited")
        batch.drop_column("window_next_edge_at")
        batch.drop_column("window_parked_from")
        batch.drop_column("budget_partial_pricing")
    op.drop_table("ledger_runs")
    op.drop_table("ledger_balance_money")
    op.drop_table("ledger_balances")
    op.drop_index("ix_ledger_entries_run", table_name="ledger_entries")
    op.drop_index("ix_ledger_entries_occurred_at", table_name="ledger_entries")
    op.drop_table("ledger_entries")
